FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24.6@sha256:2c89c41fb9efc3807029b59af69645867cfe978d2b877d475be0d72f6c6ce6f6 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-gpgsign"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-gpgsign"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-gpgsign"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-gpgsign"

ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache gnupg && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/wp-gpgsign /bin/wp-gpgsign
ENTRYPOINT ["/bin/wp-gpgsign"]
