FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.23.3@sha256:b2ca38170893394183f940a7f988bf15c4112a4ddb73214941fe4d08a09f9329 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.20@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-gpgsign"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-gpgsign"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-gpgsign"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-gpgsign"

ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache gnupg && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/wp-gpgsign /bin/wp-gpgsign
ENTRYPOINT ["/bin/wp-gpgsign"]
